### ISSUE TITLE
React.createElement

### ISSUE THREAD

**Issue by tleunen** [steida/react-externs#20]
I'm not sure why.. But I don't see React.createElement in the extern file, and this function is not renamed by the Closure Compiler. Maybe I'm missing something, but we should probably add it into the extern file as well.

**Comment by steida** [comment]
When something is defined in externs, Closure Compiler never rename such property anywhere. createElement is defined on document, so that's why.

**Comment by tleunen** [comment]
Even if it's not on the same object? React vs document? Wow.. I didn't know that.
Thanks ;)
