### ISSUE TITLE
Can I publish this to npm and bower?

### ISSUE THREAD

**Issue by teppeis** [steida/react-externs#24]
I'll add @steida and @tleunen to collaborators. ok?

**Comment by steida** [comment]
ok

**Comment by tleunen** [comment]
Not sure it's really needed for this specific usecase.
You always want people to get the latest version of this package, so having to publish to npm/bower is just an extra step that we could avoid.

**Comment by steida** [comment]
agrred

**Comment by teppeis** [comment]
* easy to install `npm i -S react-externs`
* easy to control the version

react-externs@0.13.x is for react@0.13.x (correct?).
react@0.14 has breaking changes.
For example, `React.addons.classSet` will removed.
If this package is published to npm, users can control the version easily.

**Comment by tleunen** [comment]
Hmm... Yeah I guess if we remove something and people still use an old version of React, that could cause an issue...

**Comment by teppeis** [comment]
With #25, no extra steps to publish!
If are you ok, please merge it. I'll publish.

**Comment by lukas-vlcek** [comment]
@tleunen I am interested in specific version of react externs. Not everyone want or can to live on the edge all the time.

**Comment by tleunen** [comment]
Please add @steida and myself as collaborators on npm as well. (My login is the same, not sure for steida).
https://docs.npmjs.com/cli/owner

**Comment by teppeis** [comment]
I published to npm and bower, and added @steida and @tleunen to npm owners.
Thanks!
